blank_issues_enabled: false
contact_links:
  - name: Need Help
    url: https://github.com/Zhengqbbb/starter-cli
    about: Please ask questions in Discussion.

  - name: FAQ
    url: https://github.com/Zhengqbbb/starter-cli#README
    about: Frequently Asked Questions
